version: 2.1

jobs:
  lint: 
    docker:
      - image: python:latest
    steps:
      - checkout
      - restore_cache:
          key: pip-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            
            make setup
            make install
      - save_cache:
          key: pip-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - .venv
      
      - run:
          name: run lint
          command: |
            make setup
            make lint 
  
  build-docker:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:${CIRCLE_WORKFLOW_ID:0:7} .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:${CIRCLE_WORKFLOW_ID:0:7}
        
workflows:
  default:
    jobs:
      - lint
      - build-docker:
          requires: [lint]
  # deploy-infrastructure:
  #   docker: 
  #     - image: amazon/aws-cli:latest
  #   steps:
  #     - checkout
  #     - run:
  #         name: deploy infrastructure
  #         command: |
  #           aws cloudformation deploy --template-file ./cloudformation.yml --stack-name "shine102-${CIRCLE_WORKFLOW_ID:0:7}" --capabilities CAPABILITY_IAM --region $AWS_REGION

