version: 2.1

jobs:
  lint-test: 
    docker:
      - image: python:latest
    steps:
      - checkout
      - restore_cache:
          key: pip-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            make setup
            make install
      - save_cache:
          key: pip-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - .venv
      
      - run:
          name: run lint
          command: |
            make setup
            make lint

      - run:
          name: run test
          command: |
            make setup
            make test
  
  build-docker:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:${CIRCLE_WORKFLOW_ID:0:7} .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:${CIRCLE_WORKFLOW_ID:0:7}
        
workflows:
  default:
    jobs:
      - lint-test
      - build-docker:
          requires: [lint-test]
  # deploy-infrastructure:
  #   docker: 
  #     - image: amazon/aws-cli:latest
  #   steps:
  #     - checkout
  #     - run:
  #         name: deploy infrastructure
  #         command: |
  #           aws cloudformation deploy --template-file ./cloudformation.yml --stack-name "shine102-${CIRCLE_WORKFLOW_ID:0:7}" --capabilities CAPABILITY_IAM --region $AWS_REGION

